### ISSUE TITLE
SQL Error when trying to enable

### ISSUE THREAD

**Issue by Tankyspanky** [bbDKP/PBWoW3ext#1]
Hello,
After downloading the new version i removed the old one first, Uninstall data en then removed it
Uploaded the new version.
And trying to enable it i got the following SQL Error 
========================
General Error
SQL ERROR [ mysqli ]
Duplicate entry '83-1-12' for key 'PRIMARY' [1062]
SQL
INSERT INTO phpbb_profile_fields_lang (field_id, lang_id, option_id, field_type, lang_value) VALUES ('83', '1', '12', 'profilefields.type.dropdown', 'Demon Hunter'), ('87', '1', '12', 'profilefields.type.dropdown', 'Demon Hunter')
BACKTRACE
====================================================

**Comment by Sajaki** [comment]
v3.0.2 did not have an uninstaller, so any values you added manually cause an unique exception error. 
So solution is to install v3.0.3 (ignore error) / uninstall v3.0.3 and then to reinstall v3.0.3 again.

**Comment by Tankyspanky** [comment]
Hello,

Ive tried that, but still same:
==================
General Error
SQL ERROR [ mysqli ]
Duplicate entry '100-1-12' for key 'PRIMARY' [1062]
SQL
INSERT INTO phpbb_profile_fields_lang (field_id, lang_id, option_id, field_type, lang_value) VALUES ('100', '1', '12', 'profilefields.type.dropdown', 'Demon Hunter'), ('104', '1', '12', 'profilefields.type.dropdown', 'Demon Hunter')
BACKTRACE
FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()
FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 855
CALL: trigger_error()
FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()
FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 650
CALL: phpbb\db\driver\mysqli->sql_query()
FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 377
CALL: phpbb\db\driver\driver->sql_multi_insert()
FILE: [ROOT]/ext/paybas/pbwow/migrations/release_3_0_3.php
LINE: 55
CALL: phpbb\db\driver\factory->sql_multi_insert()
FILE: (not given by php)
LINE: (not given by php)
CALL: paybas\pbwow\migrations\release_3_0_3->insert_demon_hunter()
FILE: [ROOT]/phpbb/db/migrator.php
LINE: 550
CALL: call_user_func_array()
FILE: [ROOT]/phpbb/db/migrator.php
LINE: 496
CALL: phpbb\db\migrator->run_step()
FILE: [ROOT]/phpbb/db/migrator.php
LINE: 322
CALL: phpbb\db\migrator->process_data_step()
FILE: [ROOT]/phpbb/db/migrator.php
LINE: 202
CALL: phpbb\db\migrator->try_apply()
FILE: [ROOT]/phpbb/db/migrator.php
LINE: 185
CALL: phpbb\db\migrator->update_do()
FILE: [ROOT]/phpbb/extension/base.php
LINE: 80
CALL: phpbb\db\migrator->update()
FILE: [ROOT]/phpbb/extension/manager.php
LINE: 187
CALL: phpbb\extension\base->enable_step()
FILE: [ROOT]/includes/acp/acp_extensions.php
LINE: 177
CALL: phpbb\extension\manager->enable_step()
FILE: [ROOT]/includes/functions_module.php
LINE: 674
CALL: acp_extensions->main()
FILE: [ROOT]/adm/index.php
LINE: 83
CALL: p_master->load_active()
===================================

But with the same result, 

Even after uninstalling BBguild and removing data
