### ISSUE TITLE
Version Check fatal error

### ISSUE THREAD

**Issue by khaiba** [bbDKP/PBWoW3ext#3]
After installing the newest release of the extension, and updating my board to 3.1.10, I enable the extension and when I go to the extensions tab in the adcp, it returns the following error:

`Fatal error: Uncaught exception 'RuntimeException' with message 'Connection timed out' in /usr/www/warguild/public/board/phpbb/version_helper.php:276 Stack trace: #0 /usr/www/warguild/public/board/phpbb/version_helper.php(234): phpbb\version_helper->get_versions(false, false) #1 /usr/www/warguild/public/board/ext/paybas/pbwow/acp/pbwow_module.php(514): phpbb\version_helper->get_versions_matching_stability(false, false) #2 /usr/www/warguild/public/board/ext/paybas/pbwow/acp/pbwow_module.php(100): paybas\pbwow\acp\pbwow_module->version_check(false) #3 /usr/www/warguild/public/board/includes/functions_module.php(674): paybas\pbwow\acp\pbwow_module->main('\\paybas\\pbwow\\a...', 'overview') #4 /usr/www/warguild/public/board/adm/index.php(81): p_master->load_active() #5 {main} thrown in /usr/www/warguild/public/board/phpbb/version_helper.php on line 276`

It's not returning the current version in the version checks. When I go to view the details on the extension, it shows this: 
`Failed to obtain latest version information.
Connection timed out
Re-Check version`

**Comment by Galixte** [comment]
Hi @Sajaki,

coul you take a look, please ?

**Comment by khaiba** [comment]
I managed to work around it by downloading the json from the arathe.br address and put it on my own host and edited the json's to direct to my host to bypass connection to the .br domain. That fixed it for me. Not sure why my host wont allow connection to the .br domain but that was the issue. Just means I will have a bit more work when updating in the future... but great extension otherwise!

**Comment by Sajaki** [comment]
it's a "be" domain, not "br". the 
www.avathar.be/versioncheck/pbwowext.json
sorry can't duplicate your issue.
